apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-node
  name: cicd-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd-node
  template:
    metadata:
      labels:
        app: cicd-node
    spec:
      containers:
      - image: dusrbpoiiij/cicd-node
        name: cicd-node
        ports:
        - containerPort: 3000