apiVersion: v1
kind: Service
metadata:
  labels:
    app: cicd-node-service
  name: cicd-node-service
spec:
  ports:
  - name: nodejs-port
    nodePort: 32000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cicd-node
  type: NodePort